apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
          - containerPort: 8443
          env: 
          - name: mongo_password
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db_password
