apiVersion: v1
kind: Service
metadata:
  name: rest-service-service
  namespace: default
spec:
  type: NodePort

  selector:
    app: rest-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30300
