apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-service
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      containers:
        - name: rest-service
          image: carol018/taller3:3.0.0
          ports:
          - containerPort: 4000
          env:
          - name: APP_VERSION
            value: "1.1.0"
          - name: PORT
            value: "4000"
          - name: STAGE
            value: "prod"
          - name: orgId
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: orgId
          - name: baseUrl
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: baseUrl
          - name: SecretsUser
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db_user
          - name: SecretsPassword
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db_password

