apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  db_user: Y2Fyb2xsaXNzZXRoMjY4NA==
  db_password: SmFkZTI2ODQ=

#carollisseth2684
#Jade2684
#[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("Jade2684"))